### ISSUE TITLE
How to use custom code or one of the *.m files located at data/%task%/ to generate *.mat file

### ISSUE THREAD

**Issue by brandnew2017** [acecreamu/deep-hs-prior#2]
I don't know how to run .m file in conda environment?
For example, the first line in /data/sr/prepare_sr.m:
![image](https://user-images.githubusercontent.com/32150277/68865148-46bdfb80-072d-11ea-99b0-539e8641c53a.png)

what does pavia mean? I try to use matlab in my local laptop, while it cann't find pavia:
![image](https://user-images.githubusercontent.com/32150277/68865373-afa57380-072d-11ea-84c6-a0b37b71594b.png)

I would appreciate it if you can reply me as soon as possible. Thany youvery much.

**Comment by acecreamu** [comment]
Hi, you are right, you cannot run .m files in python, you need to use matlab for it.

The second issue about pavia is much simpler than you think. Pavia is a name of a dataset (described in paper), so it's just a variable where your input data is stored. You can replace it with whatever.

**Comment by brandnew2017** [comment]
So would you mind answering my question?



---Original---

**Comment by acecreamu** [comment]
> Hi, you are right, you cannot run .m files in python, you need to use matlab for it.
> 
> The second issue about pavia is much simpler than you think. Pavia is a name of a dataset (described in paper), so it's just a variable where your input data is stored. You can replace it with whatever.

Check my previous comment.

**Comment by brandnew2017** [comment]
Thank you for your reply! I will have a try.



---Original---
